### ISSUE TITLE
CoreNLPServer doesn't fail gracefully upon Python crash

### ISSUE THREAD

**Issue by jason-fries** [HazyResearch/ddlite#105]
I don't recall this being an issue in the past, but now when Python crashes, CoreNLP doesn't exit. The next time you run the app, you get a `java.net.BindException: Address already in use' error. ` This keeps happening after CoreNLP hits a parsing issue.

**Comment by henryre** [comment]
This shows up for me frequently, but the parser still works. Did a little digging, and it looks like the pid we get from opening the server is no good since the call gets dispatched to another process. Is it crashing on that exception?

**Comment by jason-fries** [comment]
For me it hangs and I have to manually kill the java process.

**Comment by henryre** [comment]
Ok this isn't a **kill**er, but we should sort this out

**Comment by ajratner** [comment]
I'm getting this error as well

Just as an FYI for others, until we fix it; you can kill the process by running `ps aux | grep java`, finding the `pid` (the first numerical column), and then running `kill -9 <PID>`.

I'm looking into a fix for this now, by trying to kill the whole subprocess

**Comment by jason-fries** [comment]
I'll try and get the SpaCy parser implantation back to spec and push too -- people were having CoreNLP installation issues that would be nice to preempt with a simpler Python parser option as the default.

**Comment by ajratner** [comment]
Well on that front: to start let's just make sure that the install
instructions are extra clear and visible in the README... Will that solve
some of the installation issues..?

**Comment by ajratner** [comment]
On the parser issue here; I got interrupted, and won't be able to work on it this second, but as context- I was actually getting the error when trying to run one of the tests.  There was an issue with properly killing the whole process group (which I may have fixed), but my actual issue was port collision- the test was trying to start four coreNLP instances on the same port (Q: was this ever working at any point...?)

Anyway, the fix for this is just to always find an open port

@jason-fries Could your issues have been from this as well?

**Comment by henryre** [comment]
Port collisions give a Java exception, but the server is still there and the process runs. The tests always worked on my machine (and Travis' build too). I did some initial work on this in the kill-parser branch, but I couldn't massage the whole thing into compliance.

**Comment by henryre** [comment]
The real issue here is that the parser process group is not reliably killed. We can avoid the `Address already in use` exception by just trying random ports, but this would leave people with a bunch of CoreNLP servers running on their machine.

**Comment by ajratner** [comment]
Agreed.  These are two separate issues.

There's some clunky stuff with finding an open port by binding & then
closing a dummy socket...
http://stackoverflow.com/questions/1365265/on-localhost-how-to-pick-a-free-port-number.
Seems like there has to be a simpler way though, although didn't find one
yet.

As to reliably killing the process, I agree this is important. We have to
kill the whole subprocess group I think...

**Comment by henryre** [comment]
Agreed. My latest attempt is here: https://github.com/HazyResearch/ddlite/blob/kill-parser/ddlite_parser.py

atexit wasn't sufficient with real-life notebook use
