### ISSUE TITLE
Error: Could not find or load main class edu.stanford.nlp.pipeline.StanfordCoreNLPServer

### ISSUE THREAD

**Issue by raunaqrewari** [HazyResearch/ddlite#154]
Hi,
How do I solve this?

**Comment by henryre** [comment]
Hi,
Did you install the CoreNLP parser first? The README covers installation with the install-parser.sh script.

**Comment by henryre** [comment]
Closing this. @raunaqrewari, if this didn't fix your issue, let me know and I'll reopen it

**Comment by phosseini** [comment]
I think there's no more install-parser.sh(?), and I'm getting this very same error. I'm wondering if I need to install the CoreNLP myself or if there is any other solution?
