### ISSUE TITLE
Figure out why marginals sometimes still tightly concentrated around 0.5...

### ISSUE THREAD

**Issue by henryre** [HazyResearch/ddlite#163]
Avoid predictions packed tightly around 0.5

**Comment by ajratner** [comment]
Not quite sure what you mean here, but as we discussed, this is a bigger issue that may relate to still some bug in e.g. normalization in the alg; this should get fixed at the source.  Going to change title :)

**Comment by henryre** [comment]
Yeah ok agreed. My point there was that I've found it can sometimes be avoided by using, say, an initialization of 2 on the LF weights instead of 1. I don't have a consistent rule for this yet.

**Comment by henryre** [comment]
See #174
