### ISSUE TITLE
Caching Labeling Function Output: Plot Weirdness

### ISSUE THREAD

**Issue by jason-fries** [HazyResearch/ddlite#164]
Is labeling function output cached between runs? Most labeling functions don't change during dev iteration, so it would be nice to only run new or modifed LFs .

**Comment by henryre** [comment]
Do you mean the results of `apply_lfs()`? If so, don't use the `clear=True` flag.

**Comment by jason-fries** [comment]
Does this track if an LF definition changes and selectively cache then? If so, awesome! One thing I did notice when using clear-False is that the conflict plots are updated incorrectly:

<img width="380" alt="v1" src="https://cloud.githubusercontent.com/assets/348682/15266060/66e53a58-194d-11e6-9c38-749b151f9016.png">
<img width="369" alt="v2" src="https://cloud.githubusercontent.com/assets/348682/15266059/66e40e58-194d-11e6-9986-9b481ca919d2.png">

**Comment by henryre** [comment]
It doesn't track changes by function name, it just either adds to the current matrix or creates an entirely new one. Will take a look at the conflict plots!

**Comment by henryre** [comment]
Fixed in #201 (conflict metric update). Plot behavior is expected since LFs are just replicated. Doesn't make sense to cached function definitions right now, but we should give a signal to user if similar/identical LFs appear (as @jason-fries suggested in #153)
