### ISSUE TITLE
ValueError: Must have validation set if single mu not provided

### ISSUE THREAD

**Issue by raunaqrewari** [HazyResearch/ddlite#185]
Hi Henry, team,
I keep getting this error when I try to run the learning. What can I be doing wrong?

**Comment by henryre** [comment]
Hi,
If you don't set a regularization parameter (mu), ddlite will try to find one by testing a few values on your validation set. But if that doesn't exist either, it can't pick one automatically for you. You can either
1. Set an initial value (say, 1e-6) to just get learning results
2. Set a validation set using `model.set_holdout(p=x)` where 0<=`x`<=1 is the fraction of labeled examples used for the validation set and `1-x` is the fraction used for the test set.

**Comment by raunaqrewari** [comment]
Hey,
I have set the holdout to 0.5, but it doesn't work. When I pump it up to 0.9, then it starts running. Help?

Raunaq Rewari
Department of Materials Science and Engineering 
Stanford University 
+1-(650)-656-3296
raunaq@stanford.edu

**Comment by ThomasPalomares** [comment]
Hi Raunaq, do you still have this error ?
As Henry was saying, if you don't have a validation set you can try add a value of mu in your learning phase, sthg like:

%time DDL.learn_weights(sample=False, maxIter=1000, alpha=0, bias=False, verbose=True, log=True, mu=1e-6)

That should make it work. The mu is quite random here though, you may have to tune it manually if you don't provide a validation set

**Comment by henryre** [comment]
Thanks, Thomas! This will be in the next PR!
