### ISSUE TITLE
Learning weights not converging.

### ISSUE THREAD

**Issue by manyu90** [HazyResearch/ddlite#192]
I currently have 58% coverage with labeling functions in learning relations
LF stats on dev set
Coverage:	59.574%
Overlap:	26.099%
Conflict:	10.440%
Total mentions is 3525.

CM.learn_weights () keeps giving me NAN for the gradient magnitude and hence does not converge. I have also labeled 70 relations with mindtagger but I don't know if you're using mindtagger tags for learning?

**Comment by ajratner** [comment]
Hey @manyu90,

Is your notebook available to view?  If so we'd love to check out what's going on!

Thanks,
Alex

**Comment by manyu90** [comment]
Yes, I just uploaded it on github:
https://github.com/manyu90/Bacteria_drug_learning/blob/master/Bact_drug_relationLearning.ipynb

Thanks,
Abhi.

**Comment by henryre** [comment]
Hi Abhi,

It looks like some of your negative labeling functions don't output abstain values (just -1). If the function abstains from labeling, it should output a 0. This likely fixes #198 as well. Let us know.
