### ISSUE TITLE
NANs in lf_matrix

### ISSUE THREAD

**Issue by manyu90** [HazyResearch/ddlite#198]
Hey guys,

lf_matrix=CM.lf_matrix.todense()

I printed out some rows of the labeling function matrix and some of the entries are NANs instead of 1,0,-1..; not sure why this is happening?
for example:
lf_matrix[1005]:
matrix([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,
           1.,   1.,   0.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   1.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  nan,
          nan,  nan,  nan,  nan]])

**Comment by henryre** [comment]
Was this in one of the example notebooks or using a custom LF?

**Comment by manyu90** [comment]
Hey Henry,
I just fixed this. I realized my labeling functions were only returning -1 if I met the check conditions and were not returning 0 otherwise.

**Comment by henryre** [comment]
Great!
