### ISSUE TITLE
Lasso logistic regression

### ISSUE THREAD

**Issue by henryre** [HazyResearch/ddlite#23]
DeepDive can do l1 logistic regression, so ddlite should too

**Comment by ajratner** [comment]
@henryre I put this into my Julia code for data programming, which I'll put up as a repo on HazyResearch today or tomorrow

If interested though- the method we use is proximal gradient method (courtesy of CR); good reference:
https://stanford.edu/~boyd/papers/pdf/prox_algs.pdf
Specifically see sections:
* 1.1-3: Definitions / intuiton
* 4.2: Proximal gradient method
* 6.5.2: L1 norm
