### ISSUE TITLE
Add tutorial to tests suite

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/ddlite#235]
@henryre is this already done?

If not I realized we can use `nbconvert` to export the tutorial as a python script, then run this as part of tests suite

**Comment by henryre** [comment]
More or less, with @netj's slick Travis build. It just runs the notebooks with `runipy` to make sure they don't bomb out anywhere. We should start checking for expected output

**Comment by ajratner** [comment]
Okay then close this?

**Comment by henryre** [comment]
Gone
