### ISSUE TITLE
Missing GenePhenRelationExample_Learning.ipynb

### ISSUE THREAD

**Issue by SenWu** [HazyResearch/ddlite#238]
Do we have GenePhenRelationExample_Learning notebook as example? We'd better have an example for relation extraction.

**Comment by ajratner** [comment]
I know there is this notebook on the gene-pheno-demo branch, [here](https://github.com/HazyResearch/ddlite/blob/gene-pheno-demo/examples/GenePhenRelationExample_Learning.ipynb).  This is what we used for the Pentagon demo so it's current as of then... however stuff is in flux so it might be a bit old

@henryre @jason-fries Any better relation learning tutorials come to mind?

I'll be making one for chemical-disease relations, but won't be done until next week

**Comment by henryre** [comment]
No, let's wait for CDR then scrap the current ones

**Comment by SenWu** [comment]
@ajratner Thanks for pointing me that demo.

**Comment by ajratner** [comment]
@henryre Yeah that's the plan (see #226 , #221 ), but don't want to block @SenWu in the meantime

**Comment by henryre** [comment]
:+1:

**Comment by henryre** [comment]
Closing
