### ISSUE TITLE
Add raw (untokenized) text as attribute to Sentence object

### ISSUE THREAD

**Issue by jason-fries** [HazyResearch/ddlite#62]
For regex matching, it would be very helpful to have access to the text of a single sentence without any tokenization. When tagging chemical names, for example, we frequently get these tokenization type artifacts:
 Li ( 3 ) PS ( 4 ) vs.  Li(3)PS(4) 
Some of these can be fixed with modified regexes, but it would be nice to operate on the original text itself. As far as mapping back to tokens for entity tags, we could just consider a match as anything that overlaps with the original span.

**Comment by henryre** [comment]
Agreed. Would you consider this mission critical for the hackathon?

**Comment by ajratner** [comment]
@henryre We should add this in as (a) should be very quick fix and (b) not having this could be big blocking pt seems like...

**Comment by henryre** [comment]
@ajratner Check PRs
