### ISSUE TITLE
Reload tags in MindTagger

### ISSUE THREAD

**Issue by henryre** [HazyResearch/ddlite#70]
When we reopen MindTagger, we can keep the same sample as before, but not reload the tags. @netj is there a nice way to do this with the API like how we retrieve the tags, or should we form and dump `tags.json` to the instance directory?

**Comment by netj** [comment]
@henryre no there's no such api so we need to create a tags.json file from user given tags dict or list.

**Comment by henryre** [comment]
Got it!
