### ISSUE TITLE
Best practices for LF iteration

### ISSUE THREAD

**Issue by henryre** [HazyResearch/ddlite#71]
How do we illustrate best practices for debugging vs. enhancement vs. revision to new users?

**Comment by ajratner** [comment]
There are at least two dimensions:
- Efficacy: this is new ground for data programming and very exciting- how do we best get users to iterate so as to efficiently and effectively improve quality?
- Correctness / generalization: how do we push best practices for e.g. not developing and testing on the same holdout set, etc?

This will be a longer term question... but in the shorter term, @jason-fries we should all discuss together how to do this most properly for the hackathon / in the bio setting

**Comment by henryre** [comment]
+ best practices for learning
