### ISSUE TITLE
Unicode parsing issue

### ISSUE THREAD

**Issue by jason-fries** [HazyResearch/ddlite#89]
This problem didn't show up in previous ddlite versions, but certain strings now cause the parser to bomb out:

`"In addition, the isocoumarin (1) inhibited the growth of Staphylococcus aureus with the IC50 value of 87.81 µg mL(-1)."`

Converting between unicode and other encodings doesn't help. This string didn't cause problems with the default parser configuration in the past.

**Comment by henryre** [comment]
Ran into an issue like this the other day, and pushed what I thought was a universal fix. Can you send me the file you're parsing from?

**Comment by netj** [comment]
What was the cause? Long lines? Or special char striping?

**Comment by henryre** [comment]
- Long documents caused the CoreNLP server to fail (and the max char count is hardcoded in...)
- Special char stripping for plain text files was an artifact of debugging (no effect on this issue, but messed with document character offsets)
- Actual fix came from explicitly encoding strings to utf-8 before posting the request to the CoreNLP server

**Comment by netj** [comment]
So, as long as you encode input in utf-8 you can parse arbitrary length document, right?  Or does the hardcoded max length apply all the time?

(Just asking as I'm also stripping Bazaar/Parser stuff from DD :)

**Comment by henryre** [comment]
^ not sure I tested that combination. Maybe @jason-fries can chime in here.

Source for CoreNLP looks like a no though: https://github.com/stanfordnlp/CoreNLP/blob/578d7f3f89a50a4588addadb5259f3dcdaf81516/src/edu/stanford/nlp/pipeline/StanfordCoreNLPServer.java#L366

**Comment by ajratner** [comment]
We can work on this issue later, Henry a bit inundated with requests from
the PI meeting right now :)

Let's put on hold for now

**Comment by henryre** [comment]
...that sounds bad. Had a couple seconds to answer qs while this thing is training. Relations notebook incoming in < 10 min!

**Comment by jason-fries** [comment]
It sure does look like MAX_CHAR_LENGTH is the hard limit for any submitted request. I haven't hit any problems though since I've been using smallish text batches.
 
Good luck Henry fielding all those requests!
