### ISSUE TITLE
Unicode issues with CandidateModel

### ISSUE THREAD

**Issue by jason-fries** [HazyResearch/ddlite#94]
The chemnder (chemical names) training set is now causing issues in the `CandidateModel` class, throwing:
```
Traceback (most recent call last): 
  File "dd-biolib/examples/chemical_learning_demo.py", line 14, in <module>
    model = CandidateModel(candidates)
  File "dd-biolib/ddlite/ddlite.py", line 424, in __init__
    raise ValueError("Could not automatically extract features")
ValueError: Could not automatically extract features
```
due to `self.feats = self.C.extract_features()` throwing a UnicodeException `'ascii' codec can't encode character u'\u03b1' in position 0: ordinal not in range(128)`

All input text and dictionaries are parsed as utf-8. Is this possibly due to string features in treedlib casting terms out of utf-8?

**Comment by henryre** [comment]
Can you send me a file that breaks this? Did this not happen previously?

**Comment by jason-fries** [comment]
I sent the file -- it's the same offender as before (the ChemNDER training dataset).
