### ISSUE TITLE
MindTagger clips last item in display list

### ISSUE THREAD

**Issue by jason-fries** [HazyResearch/ddlite#97]
MindTagger clips the last item in a given display page, meaning you can't provide a label.  Tested on Chrome Version 49.0.2623.110 (64-bit)

![bug](https://cloud.githubusercontent.com/assets/348682/14337453/e979e556-fc22-11e5-9357-1814fccad56b.jpg)

**Comment by henryre** [comment]
@netj Any ideas?

**Comment by henryre** [comment]
Short term solutions are 1. Skip the candidate or 2. Change the number per page by one (there's some better modular arithmetic to be done here, but I'm not going to add it to Issues)

**Comment by netj** [comment]
I'll improve this..

**Comment by jason-fries** [comment]
Skipping the candidate is fine -- it's a low priority issue.

**Comment by netj** [comment]
This is probably fixed by HazyResearch/mindbender@786a0dc41669abb93b5002c774a0b5b5326de216.  Can someone confirm and close? :)

**Comment by henryre** [comment]
On it

**Comment by henryre** [comment]
@netj Just reinstalled DD, and it actually looks like MT isn't displaying at all in the embedded DDLite cell. The process is running and is accessible by navigating to the port on localhost (and the last item isn't clipped :+1: ). Any change I need to make to display the instance in the notebook?

Note: this is explains some difficulties during the hackathon

**Comment by henryre** [comment]
@netj Nix the above comment (I had a hostname config issue). DDLite still downloads the last DD release, which doesn't include the clip fix. Can verify it works when DD is updated.

**Comment by netj** [comment]
Thanks for verifying!  Latest releases (0.8-STABLE and UNSTABLE) include the fix.
